const fs = require('fs');
const readline = require('readline');
const path = require('path');

const backupFilePath = path.join(__dirname, '../../zrismpsz_cny (4).sql');
const outputFilePath = path.join(__dirname, '../../update_custom_display_name.sql');

async function generateSql() {
    console.log('Starting SQL Generation (Stream Optimized)...');
    console.log(`Input Backup: ${backupFilePath}`);
    console.log(`Output SQL: ${outputFilePath}`);

    if (!fs.existsSync(backupFilePath)) {
        console.error('Error: Backup file not found!');
        process.exit(1);
    }

    const fileStream = fs.createReadStream(backupFilePath, { encoding: 'utf8', highWaterMark: 64 * 1024 });
    const writeStream = fs.createWriteStream(outputFilePath);

    writeStream.write("-- Update custom_display_name from backup display_name\n");
    writeStream.write("-- Generated by Agentic AI\n\n");

    let count = 0;
    let inTargetTable = false;
    let buffer = '';
    let processedBytes = 0;

    // We process chunk by chunk instead of readline to avoid max string length issues and precise parsing
    for await (const chunk of fileStream) {
        processedBytes += chunk.length;
        buffer += chunk;

        // Process buffer
        if (!inTargetTable) {
            // Search for INSERT INTO `users`
            // Normalized search
            const searchStr = buffer.replace(/[\r\n]+/g, ' ');
            const matchIdx = searchStr.search(/INSERT\s+INTO\s+[`"']?users[`"']?/i);

            if (matchIdx !== -1) {
                console.log("Found users insert block!");
                inTargetTable = true;
                // Cut buffer to start from VALUES if possible
                const valuesIdx = searchStr.indexOf("VALUES", matchIdx);
                if (valuesIdx !== -1) {
                    // Start parsing from after VALUES
                    // We need to map back to original buffer index... approximate for now or just consume
                    // Simpler: Just discard everything before the first '(' after VALUES
                    const startParen = buffer.indexOf('(', valuesIdx);
                    if (startParen !== -1) {
                        buffer = buffer.substring(startParen);
                    } else {
                        // Wait for more data
                        continue;
                    }
                }
            } else {
                // Keep last 1000 chars for overlap safety, discard rest
                if (buffer.length > 1000) {
                    buffer = buffer.slice(-1000);
                }
                continue;
            }
        }

        if (inTargetTable) {
            // Parse rows: (val1, val2, ...), (val1, val2, ...)
            // State machine
            let inQuote = false;
            let rowStart = -1;
            let current = '';

            // We iterate through buffer to find rows
            // We need to remove processed characters from buffer to save memory
            let i = 0;
            let lastProcessedIndex = -1;

            while (i < buffer.length) {
                const char = buffer[i];

                if (char === "'" && (i === 0 || buffer[i - 1] !== '\\')) {
                    inQuote = !inQuote;
                }

                if (!inQuote) {
                    if (char === '(') {
                        if (rowStart === -1) rowStart = i;
                    } else if (char === ')') {
                        if (rowStart !== -1) {
                            // Row complete
                            const rowContent = buffer.substring(rowStart + 1, i);
                            processRow(rowContent, writeStream);
                            count++;
                            if (count % 1000 === 0) process.stdout.write(`Generated ${count} statements...\r`);

                            rowStart = -1;
                            lastProcessedIndex = i; // Mark this point as processed
                        }
                    } else if (char === ';') {
                        // End of statement
                        console.log("\nEnd of users insert block detected.");
                        inTargetTable = false;
                        lastProcessedIndex = i;
                        // Reset for next chunks
                        break;
                    }
                }
                i++;
            }

            // Remove processed part from buffer
            if (lastProcessedIndex !== -1) {
                buffer = buffer.substring(lastProcessedIndex + 1);
            }

            // Safety: if buffer grows too big without closing paren, something is wrong
            // But a single row shouldn't be huge usually.
        }
    }

    writeStream.end();
    console.log(`\nFinished! Generated ${count} UPDATE statements.`);
}

function processRow(rowContent, writeStream) {
    // rowContent is something like: 1, 3, 'U12345', 'Name', ...
    // Need to split by comma respecting quotes
    const parts = [];
    let currentPart = '';
    let inQ = false;

    for (let j = 0; j < rowContent.length; j++) {
        const c = rowContent[j];
        if (c === "'" && (j === 0 || rowContent[j - 1] !== '\\')) {
            inQ = !inQ;
        }
        if (c === ',' && !inQ) {
            parts.push(currentPart.trim());
            currentPart = '';
        } else {
            currentPart += c;
        }
    }
    parts.push(currentPart.trim());

    // Schema: id, line_account_id, line_user_id, display_name
    if (parts.length > 3) {
        let lineUserId = parts[2];
        let displayName = parts[3];

        // Basic validation: must be quoted strings
        if (lineUserId.startsWith("'") && displayName.startsWith("'")) {
            // Avoid empty strings if desired, script said "WHERE display_name IS NOT NULL"
            if (displayName !== "''" && displayName !== "'NULL'") {
                writeStream.write(`UPDATE users SET custom_display_name = ${displayName} WHERE line_user_id = ${lineUserId};\n`);
            }
        }
    }
}

generateSql();
